service: putraserve-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1

  environment:
    T_BOOKINGS: PutraServeBookings
    T_FEEDBACK: PutraServeFeedback
    T_TICKETS: PutraServeTickets
    T_FACILITIES: PutraServeFacilities

functions:
  createBooking:
    handler: src/handlers/bookings.createBooking
    events:
      - http:
          path: bookings
          method: post
          cors: true

  listBookings:
    handler: src/handlers/bookings.listBookings
    events:
      - http:
          path: bookings
          method: get
          cors: true

  getBooking:
    handler: src/handlers/bookings.getBooking
    events:
      - http:
          path: bookings/{id}
          method: get
          cors: true

  updateBookingStatus:
    handler: src/handlers/bookings.updateBookingStatus
    events:
      - http:
          path: bookings/{id}/status
          method: put
          cors: true

  autoCompleteBookings:
    handler: src/handlers/bookings.autoCompleteBookings
    events:
      - schedule: rate(5 minutes)

  createFeedback:
    handler: src/handlers/feedback.createFeedback
    events:
      - http:
          path: feedback
          method: post
          cors: true

  listVenues:
    handler: src/handlers/facilities.listVenues
    events:
      - http:
          path: venues
          method: get
          cors: true

  getFacility:
    handler: src/handlers/facilities.getFacility
    events:
      - http:
          path: facilities/{id}
          method: get
          cors: true

  listFacilityFeedback:
    handler: src/handlers/facilities.listFacilityFeedback
    events:
      - http:
          path: facilities/{id}/feedback
          method: get
          cors: true

  getTimeSlots:
    handler: src/handlers/facilities.getTimeSlots
    events:
      - http:
          path: facilities/{id}/timeslots
          method: get
          cors: true

  listTickets:
    handler: src/handlers/admin.listTickets
    events:
      - http:
          path: admin/tickets
          method: get
          cors: true

  updateTicketStatus:
    handler: src/handlers/admin.updateTicketStatus
    events:
      - http:
          path: admin/tickets/{id}
          method: patch
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    disableCookieValidation: true
